### ISSUE TITLE
ExtraSlots - enhancement suggestion: *edible* slots

### ISSUE THREAD

**Issue by BETLOG** [shudnal/ExtraSlots#16]
Personal preference observation:
I am more likely to have 3 potions and 5 food items than vice versa, so making the food slots able to contain potions would be more flexible. Even though they dont have a hotkey.

**Comment by shudnal** [comment]
3 extra slots for food corresponds with 3 foods that could be eaten at once. Food is not used reactively unlike potions. That's why food slots doesn't have its own hotbar. If you have more than 3 food I guess it's situational food and it could be stored in quickslots or regular inventory.
You can change amount of quick slots as you wish to store anything you need. And you can always add regular inventory row if you have more items.
I don't think I will change layout of extra slots panel.

**Comment by BETLOG** [comment]
>Food is not used reactively unlike potions.

If I had a dollar for every time I found myself suddenly realising I needed to eat, mid-battle, I'd have several dozen dollars.
That said, I prefer to weight-reduce my food by putting it in a backpack, so quickkeys cant help me there anyway.
